import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local"
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const interFont = localFont({
  src: "./fonts/Inter.ttf",
  weight: "400 700",
  variable: "--font-inter"
})

const playfairDisplayFont = localFont({
  src: "./fonts/PlayFairDisplay.ttf",
  variable: "--font-playfair-display",
  weight: "100 400 700"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playfairDisplayFont.variable} ${interFont.variable}`}>
        <header>
          <div className="site-logo">
            <h2>Universo em foco</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora atque omnis optio ipsam ratione numquam!</p>
          </div>
          <nav>
            <Link href="/">Início</Link>
            {" | "}
            <Link href="/blog">Blog</Link>
            {" | "}
            <Link href="/loja">Loja</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
