import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const interFont = localFont({
  src: "./fonts/Inter.ttf",
  weight: "400 700",
  variable: "--font-inter"
})

const playfairDisplayFont = localFont({
  src: "./fonts/PlayFairDisplay.ttf",
  variable: "--font-playfair-display",
  weight: "100 400 700"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playfairDisplayFont.variable} ${interFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
